---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.envoyproxy.io
  resources:
  - envoyproxies
  verbs:
  - get
  - patch
- apiGroups:
  - upgrade.noxbound.com
  resources:
  - talosupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - upgrade.noxbound.com
  resources:
  - talosupgrades/status
  verbs:
  - get
  - patch
  - update
